/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    landing: Landing;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Imágenes del carrusel de casos de uso y otros recursos visuales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe la imagen para accesibilidad y SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Todos los textos e imágenes visibles en lawyertec.com. Guarda para publicar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  /**
   * Aparece en la barra de navegación de todas las páginas.
   */
  nav: {
    /**
     * Enlace que lleva a la sección de funciones.
     */
    functionsLabel: string;
    /**
     * Enlace que lleva a la sección de pasos.
     */
    howItWorksLabel: string;
    /**
     * Texto del botón blanco en la esquina superior derecha.
     */
    waitlistCta: string;
  };
  /**
   * Título grande, descripción y formulario de lista de espera compacto.
   */
  hero: {
    /**
     * Píldora pequeña sobre el título (p. ej. «IA legal para abogados…»).
     */
    badge: string;
    /**
     * Primera línea del titular principal.
     */
    titleLine1: string;
    /**
     * Segunda línea con efecto visual destacado.
     */
    titleHighlight: string;
    /**
     * Párrafo bajo el titular.
     */
    description: string;
  };
  /**
   * Lista desplazable de fuentes legales bajo el hero.
   */
  marquee: {
    /**
     * Texto sobre la cinta animada.
     */
    heading: string;
    sources?:
      | {
          /**
           * Nombre del código o ley (p. ej. Código Civil Federal).
           */
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Simulación de conversación legal en la caja del hero.
   */
  chatDemo: {
    /**
     * Etiqueta en la barra superior del chat.
     */
    projectTitle: string;
    /**
     * Burbuja de pregunta del abogado.
     */
    question: string;
    tools?:
      | {
          label: string;
          icon: 'search' | 'calc' | 'brain';
          id?: string | null;
        }[]
      | null;
    /**
     * Texto de respuesta del agente.
     */
    answer: string;
    highlightTerms?:
      | {
          /**
           * Palabra o frase resaltada en dorado en la respuesta.
           */
          term: string;
          id?: string | null;
        }[]
      | null;
    footerNote: string;
  };
  /**
   * Cada bloque es una sección del sitio. Usa «Añadir bloque» para insertar secciones y arrastra para cambiar el orden.
   */
  sections?:
    | (
        | {
            /**
             * Texto pequeño en mayúsculas sobre el título.
             */
            eyebrow: string;
            title: string;
            subtitle: string;
            items?:
              | {
                  title: string;
                  description: string;
                  /**
                   * Ícono visual de la tarjeta (no editable, solo estilo).
                   */
                  icon: 'research' | 'document' | 'memory' | 'projects';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            items?:
              | {
                  /**
                   * Número o cifra (p. ej. +300, 24/7).
                   */
                  value: string;
                  /**
                   * Descripción breve bajo la cifra.
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Texto pequeño en mayúsculas sobre el título.
             */
            eyebrow: string;
            title: string;
            subtitle: string;
            items?:
              | {
                  /**
                   * Arrastra una foto o elige de la biblioteca de imágenes.
                   */
                  image: number | Media;
                  title: string;
                  caption: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'useCases';
          }
        | {
            /**
             * Texto pequeño en mayúsculas sobre el título.
             */
            eyebrow: string;
            title: string;
            subtitle: string;
            steps?:
              | {
                  /**
                   * P. ej. 01, 02, 03.
                   */
                  num: string;
                  title: string;
                  text: string;
                  /**
                   * Tipo de mini-vista previa bajo cada paso.
                   */
                  previewStyle: 'simple' | 'tags' | 'citation';
                  /**
                   * Texto mostrado en la mini-vista previa.
                   */
                  previewText?: string | null;
                  /**
                   * Parte resaltada en color dorado (p. ej. Art. 1792 CCF).
                   */
                  previewHighlight?: string | null;
                  previewTags?:
                    | {
                        tag: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'howItWorks';
          }
        | {
            /**
             * Primera parte del titular (antes de la palabra destacada).
             */
            title: string;
            /**
             * Palabra con efecto visual (p. ej. «anticipado»).
             */
            titleHighlight: string;
            description: string;
            /**
             * Texto pequeño bajo el formulario.
             */
            footnote: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'waitlist';
          }
      )[]
    | null;
  /**
   * Título y descripción que aparecen en Google y al compartir el enlace.
   */
  seo: {
    /**
     * Aparece en la pestaña del navegador y en resultados de búsqueda.
     */
    title: string;
    /**
     * Resumen de 1–2 oraciones para buscadores.
     */
    description: string;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        functionsLabel?: T;
        howItWorksLabel?: T;
        waitlistCta?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleHighlight?: T;
        description?: T;
      };
  marquee?:
    | T
    | {
        heading?: T;
        sources?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  chatDemo?:
    | T
    | {
        projectTitle?: T;
        question?: T;
        tools?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        answer?: T;
        highlightTerms?:
          | T
          | {
              term?: T;
              id?: T;
            };
        footerNote?: T;
      };
  sections?:
    | T
    | {
        features?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        useCases?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        howItWorks?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              steps?:
                | T
                | {
                    num?: T;
                    title?: T;
                    text?: T;
                    previewStyle?: T;
                    previewText?: T;
                    previewHighlight?: T;
                    previewTags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        waitlist?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              description?: T;
              footnote?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}